// Shed Model - Trusses
include <dimensions.scad>
include <truss_data.scad>
include <end_truss_data.scad>

// ============================================
// TRUSS MODULES (Queen-Post Design)
// ============================================
// Queen-post truss with 6/12 pitch, no N/S eave overhang
// Spans N-S (Y direction), positioned along X to align with south wall studs
//
// Truss members are polyhedra generated by generate-truss-data.js
// with plumb cuts on rafters and angled cuts on queen posts.

// Single queen-post truss at X position
// Truss sits on top of double top plate of walls
// alpha parameter controls transparency (1.0 = opaque, 0.25 = mostly transparent)
module queen_post_truss(x_pos, alpha = 1.0) {
    echo(str("CUTLIST,Truss bottom chord (x=", x_pos, "),2x4,1,144\""));
    echo(str("CUTLIST,Truss south rafter (x=", x_pos, "),2x4,1,80.5\" plumb cuts 26.6°"));
    echo(str("CUTLIST,Truss north rafter (x=", x_pos, "),2x4,1,80.5\" plumb cuts 26.6°"));
    echo(str("CUTLIST,Truss south queen post (x=", x_pos, "),2x4,1,22.3\" angle cut 26.6°"));
    echo(str("CUTLIST,Truss north queen post (x=", x_pos, "),2x4,1,22.3\" angle cut 26.6°"));
    echo(str("CUTLIST,Truss straining beam (x=", x_pos, "),2x4,1,48\""));
    echo(str("CUTLIST,Peak gusset (x=", x_pos, "),1/2\" plywood,2,12\" x 19.4\" pentagon"));
    echo(str("CUTLIST,QP top gusset south (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    echo(str("CUTLIST,QP top gusset north (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    echo(str("CUTLIST,QP bottom gusset south (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    echo(str("CUTLIST,QP bottom gusset north (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    echo(str("CUTLIST,Eave gusset south (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    echo(str("CUTLIST,Eave gusset north (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    color(color_truss, alpha)
    translate([x_pos, 0, wall_top_z]) {
        truss_bottom_chord();
        truss_south_rafter();
        truss_north_rafter();
        truss_south_queen_post();
        truss_north_queen_post();
        truss_straining_beam();
    }
    color(color_gusset, alpha)
    translate([x_pos, 0, wall_top_z]) {
        truss_peak_gusset();
        truss_south_qp_top_gusset();
        truss_north_qp_top_gusset();
        truss_south_qp_bottom_gusset();
        truss_north_qp_bottom_gusset();
        truss_south_eave_gusset();
        truss_north_eave_gusset();
    }
}

// End truss at a gable wall position
// Includes notched rafters and vertical studs (no queen posts/straining beam)
module end_truss(x_pos, alpha = 1.0) {
    echo(str("CUTLIST,End truss bottom chord (x=", x_pos, "),2x6,1,144\""));
    echo(str("CUTLIST,End truss south rafter (x=", x_pos, "),2x6,1,80.5\" plumb cuts"));
    echo(str("CUTLIST,End truss north rafter (x=", x_pos, "),2x6,1,80.5\" plumb cuts"));
    // Stud cut list from generated data (9 studs + 2 end fillers per truss)
    // Bounding-box height = max(zTopLeft, zTopRight) - zBottom, matching the
    // actual polyhedron profile in end_truss_data.scad.
    board_gap = 0.125;
    for (i = [0 : len(end_truss_stud_ys) - 1]) {
        y = end_truss_stud_ys[i];
        y_left = y - 1.5/2;
        y_right = y + 1.5/2;
        rafter_angle = atan(truss_pitch);
        thickness_adj = (truss_member_depth - 1.5) / cos(rafter_angle);
        chord_offset = 1.5 + truss_member_depth;
        z_top_left = chord_offset + truss_rise - abs(y_left - truss_span/2) * truss_pitch + thickness_adj - board_gap;
        z_top_right = chord_offset + truss_rise - abs(y_right - truss_span/2) * truss_pitch + thickness_adj - board_gap;
        z_bottom = 1.5 + board_gap;
        h = max(z_top_left, z_top_right) - z_bottom;
        echo(str("CUTLIST,End truss stud ", i, " (x=", x_pos, " y=", y, "),2x6,1,", h, "\" angle cut top 26.6°"));
    }
    // End truss sits plate_thickness lower — its bottom chord acts as E/W wall's 2nd top plate
    color(color_truss, alpha)
    translate([x_pos, 0, wall_top_z - plate_thickness]) {
        end_truss_assembly();
    }
}

// All trusses at 24" o.c.
module trusses() {
    truss_spacing = 24;  // 24" on center
    num_trusses = floor(shed_length / truss_spacing) + 1;  // 9 trusses

    for (i = [0 : num_trusses - 1]) {
        x_pos = i * truss_spacing;
        if (i == 0) {
            // West end truss: outer face flush with wall stud face
            end_truss(x_pos + stud_depth/2);
        } else if (i == num_trusses - 1) {
            // East end truss: outer face flush with wall stud face
            end_truss(x_pos - stud_depth/2);
        } else {
            queen_post_truss(x_pos);
        }
    }
}

