// Shed Model - Trusses and Ladder Framing
include <dimensions.scad>
include <truss_data.scad>
include <end_truss_data.scad>

// ============================================
// TRUSS MODULES (Queen-Post Design)
// ============================================
// Queen-post truss with 6/12 pitch, no N/S eave overhang
// Spans N-S (Y direction), positioned along X to align with south wall studs
//
// Truss members are polyhedra generated by generate-truss-data.js
// with plumb cuts on rafters and angled cuts on queen posts.

// Single queen-post truss at X position
// Truss sits on top of double top plate of walls
// alpha parameter controls transparency (1.0 = opaque, 0.25 = mostly transparent)
module queen_post_truss(x_pos, alpha = 1.0) {
    echo(str("CUTLIST,Truss bottom chord (x=", x_pos, "),2x4,1,144\""));
    echo(str("CUTLIST,Truss south rafter (x=", x_pos, "),2x4,1,80.5\" plumb cuts 26.6°"));
    echo(str("CUTLIST,Truss north rafter (x=", x_pos, "),2x4,1,80.5\" plumb cuts 26.6°"));
    echo(str("CUTLIST,Truss south queen post (x=", x_pos, "),2x4,1,22.3\" angle cut 26.6°"));
    echo(str("CUTLIST,Truss north queen post (x=", x_pos, "),2x4,1,22.3\" angle cut 26.6°"));
    echo(str("CUTLIST,Truss straining beam (x=", x_pos, "),2x4,1,48\""));
    echo(str("CUTLIST,Peak gusset (x=", x_pos, "),1/2\" plywood,2,12\" x 19.4\" pentagon"));
    echo(str("CUTLIST,QP top gusset south (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    echo(str("CUTLIST,QP top gusset north (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    echo(str("CUTLIST,QP bottom gusset south (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    echo(str("CUTLIST,QP bottom gusset north (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    echo(str("CUTLIST,Eave gusset south (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    echo(str("CUTLIST,Eave gusset north (x=", x_pos, "),1/2\" plywood,2,10\" x 8\""));
    color(color_truss, alpha)
    translate([x_pos, 0, wall_top_z]) {
        truss_bottom_chord();
        truss_south_rafter();
        truss_north_rafter();
        truss_south_queen_post();
        truss_north_queen_post();
        truss_straining_beam();
    }
    color(color_gusset, alpha)
    translate([x_pos, 0, wall_top_z]) {
        truss_peak_gusset();
        truss_south_qp_top_gusset();
        truss_north_qp_top_gusset();
        truss_south_qp_bottom_gusset();
        truss_north_qp_bottom_gusset();
        truss_south_eave_gusset();
        truss_north_eave_gusset();
    }
}

// End truss at a gable wall position
// Includes notched rafters and vertical studs (no queen posts/straining beam)
module end_truss(x_pos, alpha = 1.0) {
    echo(str("CUTLIST,End truss bottom chord (x=", x_pos, "),2x4,1,144\""));
    echo(str("CUTLIST,End truss south rafter (x=", x_pos, "),2x4,1,80.5\" plumb cuts"));
    echo(str("CUTLIST,End truss north rafter (x=", x_pos, "),2x4,1,80.5\" plumb cuts"));
    echo(str("CUTLIST,End truss south stud 0 (x=", x_pos, "),2x4,1,5.375\" angle cut top 26.6°"));
    echo(str("CUTLIST,End truss south stud 1 (x=", x_pos, "),2x4,1,15.875\" angle cut top 26.6°"));
    echo(str("CUTLIST,End truss south stud 2 (x=", x_pos, "),2x4,1,26.375\" angle cut top 26.6°"));
    echo(str("CUTLIST,End truss north stud 0 (x=", x_pos, "),2x4,1,5.375\" angle cut top 26.6°"));
    echo(str("CUTLIST,End truss north stud 1 (x=", x_pos, "),2x4,1,15.875\" angle cut top 26.6°"));
    echo(str("CUTLIST,End truss north stud 2 (x=", x_pos, "),2x4,1,26.375\" angle cut top 26.6°"));
    color(color_truss, alpha)
    translate([x_pos, 0, wall_top_z]) {
        end_truss_assembly();
    }
}

// Ladder framing for one gable end: outriggers + fly rafters
// x_pos = end truss X position, side = -1 for west (overhang toward -X), +1 for east
module ladder_framing(x_pos, side = -1, alpha = 1.0) {
    side_label = side == -1 ? "west" : "east";
    echo(str("CUTLIST,Fly rafter south (", side_label, "),2x4,1,80.5\" plumb cuts"));
    echo(str("CUTLIST,Fly rafter north (", side_label, "),2x4,1,80.5\" plumb cuts"));
    echo(str("CUTLIST,Outriggers (", side_label, "),2x4,6,36\""));
    color(color_ladder, alpha)
    translate([x_pos, 0, wall_top_z]) {
        // Outriggers are generated with X from -gable_overhang to +24
        // For west end (side=-1): outriggers extend from X=-12 to X=+24 relative to end truss — correct as-is
        // For east end (side=+1): mirror in X so overhang goes the other way
        if (side == 1) {
            mirror([1, 0, 0]) {
                end_truss_outriggers();
                end_truss_fly_rafters();
            }
        } else {
            end_truss_outriggers();
            end_truss_fly_rafters();
        }
    }
}

// All trusses at 24" o.c.
module trusses() {
    truss_spacing = 24;  // 24" on center
    num_trusses = floor(shed_length / truss_spacing) + 1;  // 9 trusses

    for (i = [0 : num_trusses - 1]) {
        x_pos = i * truss_spacing;
        if (i == 0 || i == num_trusses - 1) {
            end_truss(x_pos);
        } else {
            queen_post_truss(x_pos);
        }
    }
}

// All ladder framing (called separately from shed_model.scad)
module ladder_framing_all() {
    ladder_framing(0, -1);                    // West end, overhang toward -X
    ladder_framing(shed_length, 1);           // East end, overhang toward +X
}
