// Shed Model - Trusses and Ladder Framing
include <dimensions.scad>
include <truss_data.scad>

// ============================================
// TRUSS MODULES (Queen-Post Design)
// ============================================
// Queen-post truss with 6/12 pitch, 1' overhang
// Spans N-S (Y direction), positioned along X to align with south wall studs
//
// Truss members are polyhedra generated by generate-truss-data.js
// with plumb cuts on rafters and angled cuts on queen posts.

// Angled truss member for ladder framing (fly rafters)
module angled_member(start_y, start_z, end_y, end_z) {
    dy = end_y - start_y;
    dz = end_z - start_z;
    length = sqrt(dy*dy + dz*dz);
    angle = atan2(dz, dy);

    translate([0, (start_y + end_y)/2, (start_z + end_z)/2])
        rotate([angle, 0, 0])
            cuboid([truss_member_width, length, truss_member_depth], anchor = CENTER);
}

// Single queen-post truss at X position
// Truss sits on top of double top plate of walls
// alpha parameter controls transparency (1.0 = opaque, 0.25 = mostly transparent)
module queen_post_truss(x_pos, alpha = 1.0) {
    color(color_truss, alpha)
    translate([x_pos, 0, wall_top_z]) {
        truss_bottom_chord();
        truss_south_rafter();
        truss_north_rafter();
        truss_south_queen_post();
        truss_north_queen_post();
        truss_straining_beam();
    }
}

// All trusses at 24" o.c.
module trusses() {
    truss_spacing = 24;  // 24" on center
    num_trusses = floor(shed_length / truss_spacing) + 1;  // 9 trusses

    for (i = [0 : num_trusses - 1]) {
        x_pos = i * truss_spacing;
        is_end_truss = (i == 0) || (i == num_trusses - 1);
        queen_post_truss(x_pos);
    }
}

// ============================================
// LADDER FRAMING (Gable End Overhangs)
// ============================================
// Lookouts extend from second truss past end truss to fly rafter
// Creates the gable overhang on east and west ends

// Single lookout at a given Y position
// Extends from interior_truss_x past end_truss_x to fly_rafter_x
// Lookouts lie in the roof plane (rotated to match roof slope)
module lookout(y_pos, interior_x, fly_rafter_x) {
    lookout_length = abs(fly_rafter_x - interior_x);
    center_x = (interior_x + fly_rafter_x) / 2;

    // Rafter top at this Y position
    rafter_top_z = rafter_bottom_z_at_y(y_pos) + truss_member_depth;

    // Roof angle (positive value)
    roof_angle = atan(truss_pitch);  // ~26.57 degrees for 6/12

    // Determine which side of peak we're on
    center_y = shed_width / 2;
    is_south_side = (y_pos < center_y);

    // Rotation direction: south side tilts up toward center, north side tilts up toward center
    rot_angle = is_south_side ? roof_angle : -roof_angle;

    // Position lookout so its top surface is in the roof plane
    // After rotation, offset down by half the thickness (perpendicular to roof surface)
    z_offset = lookout_width / 2 * cos(roof_angle);
    y_offset = lookout_width / 2 * sin(roof_angle) * (is_south_side ? -1 : 1);

    color(color_truss, 0.25)
        translate([center_x, y_pos + y_offset, rafter_top_z - z_offset])
            rotate([rot_angle, 0, 0])
                cuboid([lookout_length, lookout_depth, lookout_width], anchor = CENTER);
}

// Fly rafter (runs parallel to main rafters at outer edge of lookouts)
// Top surface is coplanar with main rafters for flat roof sheathing
module fly_rafter(x_pos) {
    bottom_chord_top = wall_top_z + truss_member_depth;
    rafter_bottom_at_wall = bottom_chord_top;
    rafter_bottom_at_peak = bottom_chord_top + truss_rise;
    rafter_bottom_at_overhang = rafter_bottom_at_wall - truss_overhang * truss_pitch;

    south_end = -truss_overhang;
    north_end = shed_width + truss_overhang;
    center_y = shed_width / 2;

    // Fly rafter is coplanar with main rafters (no z_offset)
    color(color_truss, 0.25)
    translate([x_pos, 0, 0]) {
        // South side: overhang to peak
        angled_member(
            south_end, rafter_bottom_at_overhang + truss_member_depth/2,
            center_y, rafter_bottom_at_peak + truss_member_depth/2
        );

        // North side: peak to overhang
        angled_member(
            center_y, rafter_bottom_at_peak + truss_member_depth/2,
            north_end, rafter_bottom_at_overhang + truss_member_depth/2
        );
    }
}

// Complete ladder framing for both gable ends
module ladder_framing() {
    // Truss positions (from trusses module)
    truss_spacing = 24;
    west_end_truss = 0;
    west_interior_truss = 24;
    east_interior_truss = 168;
    east_end_truss = 192;

    // Fly rafter positions (overhang past walls)
    west_fly_rafter = -gable_overhang;    // -12"
    east_fly_rafter = shed_length + gable_overhang;  // 204"

    // Lookout Y positions along the rafter (from south overhang to north overhang)
    // Space them at lookout_spacing intervals
    lookout_y_positions = [
        for (y = [-truss_overhang : lookout_spacing : shed_width + truss_overhang])
            y
    ];

    // West gable ladder framing
    for (y = lookout_y_positions) {
        lookout(y, west_interior_truss, west_fly_rafter);
    }
    fly_rafter(west_fly_rafter);

    // East gable ladder framing
    for (y = lookout_y_positions) {
        lookout(y, east_interior_truss, east_fly_rafter);
    }
    fly_rafter(east_fly_rafter);
}
